### ISSUE TITLE
 I want to request to hire any property for one night

### ISSUE THREAD

**Issue by ddottyler** [PetarSimonovic/bunker_makersbnb#10]
FRONT END
Need a book button for each property listed -> take to page that says booking has been successfully requested. Button to go back to bunker.

**Comment by PetarSimonovic** [comment]
Create Booking class

Booking table:
 - Booking ID, Property ID, User ID, Confirmation Status (Default: requested, confirmed, rejected)
 -

**Comment by louiswicks** [comment]
Completed both front end and back end aspects of User Story.
